name: ChatGPT Code Updates

on:
  workflow_dispatch:  # Allows manual trigger
  pull_request:
    branches:
      - main  # Change this if your branch is different

jobs:
  update_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "ChatGPT-AI"
          git config --global user.email "your-email@example.com"

      - name: Make changes
        run: |
          echo "ChatGPT updated your code!" >> update_log.txt

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add .
          git commit -m "Automated update from ChatGPT"
          git push https://${{ secrets.GH_TOKEN }}@github.com/siliconbleach/master.git main
